server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s #tempo para concluir as operacoes antes de desligar ou matar o microservice
  datasource:
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 15
  flyway:
    sql-migration-suffixes:
      - .sql
    locations:
      - classpath:db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        cache.use_second_level_cache: false
        cache.use_query_cache: false
        generate_statistics: false
        hbm2ddl.auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
