server:
  port: 8082
  shutdown: graceful
  tomcat:
    connection-timeout: 2s #tempo minimo de conexao inativa
    keep-alive-timeout: 15s #tempo maximo do timeout
    threads:
      max: 50
      min-spare: 5


spring:
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  graphql:
    graphiql.enabled: true
    schema:
      locations: classpath:/graphql
  thread-executor: virtual
#  config:
#    import: aws-secretsmanager:test/secret/
  lifecycle:
    timeout-per-shutdown-phase: 15s #tempo para concluir as operacoes antes de desligar ou matar o microservice
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    #username: rds/credentials
    #url: jdbc-secretsmanager:postgresql://localhost:5432/postgres
    #driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver #https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_jdbc.html
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 15
  flyway:
    sql-migration-suffixes:
      - .sql
    locations:
      - classpath:db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        cache.use_second_level_cache: false
        cache.use_query_cache: false
        generate_statistics: false
        hbm2ddl.auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    info:
      enabled: true
    health:
      show-details: always
    web:
      exposure:
        include: health,metrics,prometheus,loggers
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

api:
  secret-key: teste